import os
import wifi_portal

VISUAL_X_OFFSET = 0

AP_SSID = getattr(wifi_portal, "AP_SSID", "GDSENG-SETUP")
AP_PASS = getattr(wifi_portal, "AP_PASS", "12345678")
AP_IP = getattr(wifi_portal, "AP_IP", "192.168.4.1")
PORTAL_PORT = 80

BUTTON_PIN_NEXT = 27
BUTTON_PIN_EXECUTE = 17
LED_SUCCESS = 24
LED_ERROR = 25
LED_ERROR1 = 23

SHUNT_OHMS = 0.1
MIN_VOLTAGE = 3.1
MAX_VOLTAGE = 4.2

SOFT_DEBOUNCE_NEXT = 0.05
SOFT_DEBOUNCE_EXEC = 0.05

LONG_PRESS_THRESHOLD = 0.7
NEXT_LONG_CANCEL_THRESHOLD = 0.7

STM32_POLL_INTERVAL_SEC = 0.08
STM32_POLL_LOOP_SLEEP_SEC = 0.02

STM32_CONNECT_TIMEOUT_SEC = 0.55
STM32_DETECT_TIMEOUT_SEC = 1.8
STM32_FALLBACK_PROBE_TIMEOUT_SEC = 1.2
STM32_UNLOCK_TIMEOUT_SEC = 1.4
STM32_LOCK_TIMEOUT_SEC = 1.4

STM32_DETECT_CACHE_TTL_SEC = 2.5
STM32_RECENT_UNLOCK_TTL_SEC = 2.2

PROGRAM_PROGRESS_POLL_SEC = 0.10
PROGRAM_PROGRESS_MAX_DURATION_SEC = 4.0

DEFAULT_POST_FLASH_WAIT_SEC = 0.15
POST_FLASH_WAIT_SEC = DEFAULT_POST_FLASH_WAIT_SEC

OPENOCD_IFACE = "/usr/local/share/openocd/scripts/interface/raspberrypi-native.cfg"
OPENOCD_TARGET = "/usr/local/share/openocd/scripts/target/stm32f1x.cfg"

FIRMWARE_DIR = "/home/user/stm32/Program"
OUT_SCRIPT_PATH = "/home/user/stm32/out.py"
MENU_CONFIG_CSV = "/home/user/stm32/menu_config.csv"

GENERAL_DIRNAME = "1.일반"
TFTP_DIRNAME = "2.TFTP"
GENERAL_ROOT = os.path.join(FIRMWARE_DIR, GENERAL_DIRNAME)
TFTP_ROOT = os.path.join(FIRMWARE_DIR, TFTP_DIRNAME)
FLASH_KB_THRESHOLD = 300

TFTP_REMOTE_DIR = "/home/user/stm32/Program/2.TFTP_REMOTE"
TFTP_SERVER_ROOT = "/srv/tftp"
TFTP_DEVICE_SUBDIR = os.path.join("GDS", "ASGD-3200")
TFTP_DEVICE_FILENAME = "asgd3200.bin"

GIT_REPO_DIR = "/home/user/stm32"
MODBUS_PORT = 502

REG_STATUS_4XXXX = 40001
REG_GAS_FLOAT_HI = 40003
REG_GAS_FLOAT_LO = 40004
REG_GAS_INT_4XXXX = 40005
REG_FAULT_4XXXX = 40008

SCAN_PRUNE_SEC = 12.0
SCAN_HOSTS_PER_TICK = 4
SCAN_MENU_REBUILD_MIN_SEC = 0.6
SCAN_PREFIX_STABLE_CNT = 2
SCAN_DETAIL_POLL_SEC = 0.2

FONT_PATH = "/usr/share/fonts/truetype/malgun/malgunbd.ttf"
BATTERY_ICON_PATH = "/home/user/stm32/img/bat.png"
